language: go
go_import_path: github.com/Ashwin-Rajeev/boom
go:
  - 1.13.x
  - master

script:
  - go test -race -coverprofile=coverage.txt -covermode=atomic
  
after_success:
  - bash <(curl -s https://codecov.io/bash)
