language: go
go_import_path: github.com/Ashwin-Rajeev/boom
go:
  - 1.13.x
  - master

script:
  - echo "Ensuring code is well formatted"; ! gofmt -s -d . | read
  - go test -v -coverprofile=coverage.txt -covermode=atomic -tags matprofile .
  
after_success:
  - bash <(curl -s https://codecov.io/bash)
